name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version, e.g., '3.19.0' or 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href /majhong_event_score/

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ./docs
          cp -r ./flutter_application_1/build/web/* ./docs/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Flutter web app to GitHub Pages (manual copy)"
          git push origin main
